# Generated by Django 3.2.10 on 2023-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Sector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
