# Generated by Django 3.2.10 on 2023-01-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_case_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cattleType',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
